defaultAssertionDataset: superform_assertion_266125989
defaultDataset: superform_outputs_266125989                                                                                                                                                   
defaultLocation: EU
defaultProject: husqvarna-com-ga4                                                                                                                                                             
vars:           
  GA4_DATASET: analytics_266125989
  LOCAL_TIMEZONE: Europe/Brussels                                                                                                                                                             
  OUTPUTS_DATASET: superform_outputs_266125989
  QUALITY_DATASET: superform_quality_266125989                                                                                                                                                
  TRANSFORMATIONS_DATASET: superform_transformations_266125989
  LABEL_GENERIC_BRAND: superformlabs                                                                                                                                                          
  LABEL_GENERIC_TOOL: ga4dataform
  LABEL_GENERIC_LICENSE_TYPE: core                                                                                                                                                            
  LABEL_EXECUTION_OPERATION: daily_workflow
  LABEL_GENERIC_PACKAGE_VERSION: v1-19-0